server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        
        # Désactiver le cache navigateur pour toujours servir la version fraîche
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
        add_header Last-Modified "";
        etag off;

        try_files $uri $uri/ /index.html;
    }
}
